### ISSUE TITLE
No module named nest when importing ViSAPy

### ISSUE THREAD

**Issue by kaancet** [espenhgn/ViSAPy#3]
I get this error whenever I try to run any of the examples. I already have a working NEURON and all the dependencies. I am on a Windows 10 64-bit computer (x64-based processor) 

Traceback (most recent call last):
  import ViSAPy
  File "build\bdist.win-amd64\egg\ViSAPy\__init__.py", line 12, in <module>
  File "build\bdist.win-amd64\egg\ViSAPy\networks.py", line 15, in <module>
ImportError: No module named nest

**Comment by espenhgn** [comment]
Hi @kaancet ,

Sorry for your problems running the code. 

You need to obtain NEST from www.nest-simulator.org or github.com/nest/nest-simulator. It's not pip-installable so follow their instructions for your system. Make sure that the correct Python version is found during the cmake configuration step.

**Comment by espenhgn** [comment]
Hi again, 
Sorry, NEST doesn't support Windows, so you're out of luck. If you have access to a linux/unix based cluster you may install and run things there. If it's only some test datasets you're after, I have some available as used in this preprint: https://www.biorxiv.org/content/early/2017/06/19/151928
The data can be found here: https://fz-juelich.sciebo.de/s/yhwOBRC9DzWRlof

**Comment by kaancet** [comment]
Hey @espenhgn,

Yeah, thats what I was afraid of. I wanted to create some datasets to benchmark some sorting algorithms so the datasets you provided will suffice. Thank you for your help

**Comment by espenhgn** [comment]
Sounds good @kaancet. If you end up using these datasets in future publication(s), please cite both the YASS paper and the ViSAPy paper http://dx.doi.org/10.1016/j.jneumeth.2015.01.029
